language: node_js
node_js:
- 6
- node
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: npm release
      node_js: 6
      script: npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        api_key: $NPM_TOKEN
        if: branch = master
